modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="industrialelectricity" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Industrial Electricity" #mandatory
logoFile="industrialelectricity.png" #optional
credits="Thanks to all contributors" #optional
authors="skip999" #optional
description='''
'''
[[dependencies.industrialelectricity]]
    modId="electrodynamics"
    mandatory=true
    versionRange="[1.20.1-0.9,)"
    ordering="NONE"
    side="BOTH"